### PR TITLE
Updated - Added "st" prefix for attr fields

### PR DESCRIPTION
**Pull request by alexwyattdev**

### CODE REVIEW

**Comment by Muddz** [comment]
Nice thanks! I was going to make it with this prefix `st_textsize` but yours looks better. I will merge your changes and make a new build and release when I get home in a few hours

**Comment by Muddz** [comment]
Could you make your Pull request again but just from another branch which is not a master branch?

**Comment by alexwyattdev** [comment]
I will try to do it today :)

**Comment by alexwyattdev** [comment]
I made it into a separate branch

**Pull request closed without merging**
