### PR TITLE
Added setGravity() method

### PR DESCRIPTION
**Pull request by hshrimali**
To set the position of toast on app screen.

### CODE REVIEW

**Comment by Muddz** [comment]
Hi. For what reason would a toast ever change its position on the screen?
Toast should only appear on the bottom of the screen as any other toast does in every app.

**Comment by hshrimali** [comment]
Toast like loading, searching can be shown in the middle of the screen. And toast like refreshing can be shown on the top of the screen. In simple words, It's the desire of many users to position the toast, that's why I added it.
Thank You .

**Comment by hshrimali** [comment]
@Muddz  Any suggestions? It's been long time.

**Comment by Muddz** [comment]
@hshrimali Hi. I have been working on other coding projects. But no I'm not going to add that method. 

But you can fork the project and add by yourself and add/change anything else you want.
I don't want to overflow the library with features that arent important.

**Comment by Darshan10298** [comment]
This Feature seems Nice :)

**Pull request closed without merging**
